language: python
python:
    - "3.6"
    - "3.7"
    - "3.8"
    - "3.9"
install:
    - pip install -r requirements.txt
script: |
    if [ $(python -c "import sys; print(sys.version_info.minor)") -lt 7 ]; then
        nosetests
    else
        nosetests --with-coverage --cover-package=discogs_client
    fi
after_success:
    - coveralls
